# --- !Ups

create table "redirect" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "slug" varchar not null,
  "url" varchar not null
)

# --- !Downs

drop table "redirect" if exists;
